warning: No `requires-python` value found in the workspace. Defaulting to `>=3.11`.
/home/toma/t-80-8-b-03/_work/experiment_matsuzawa_250916/experiment_matsuzawa_250916/.venv/lib/python3.11/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
2025-09-16 11:33:46,506 - INFO - Loading config config/full_experiment.yaml
2025-09-16 11:33:46,535 - WARNING - wandb initialisation failed: api_key not configured (no-tty). call wandb.login(key=[your_api_key]). Disabling.
2025-09-16 11:33:46,714 - INFO - Using device cuda
2025-09-16 11:33:46,714 - INFO - Preparing dataloaders …
2025-09-16 11:33:46,714 - INFO - Encountered template config without 'corruption'. Skipping …
2025-09-16 11:33:46,714 - INFO - Encountered template config without 'corruption'. Skipping …
2025-09-16 11:33:46,715 - INFO - Encountered template config without 'corruption'. Skipping …
2025-09-16 11:33:48,191 - WARNING - Imagenet-1k dataset gated/unavailable (Could not load dataset 'imagenet-1k' from the Hub: Dataset 'imagenet-1k' is a gated dataset on the Hub. You must be authenticated to access it.). Falling back to open 'imagenette'.
2025-09-16 11:33:48,191 - ERROR - Failed preparing dataset imagenet-c: _attempt_load_hf_dataset() got multiple values for argument 'name'
DATASET FAILED: imagenet-c
